w=window_get_width()
h=window_get_height()
time_speed=1
window_set_size(display_get_width(),display_get_height())
window_set_position(0,0)
afterImageFreq=20
afterImageDl=0
time_speed_targ=1
//window_set_cursor(cr_none);