hero=noone; //hero character owned by
target=noone; //target enemy
floatLerpAm = 5; //how quickly sword lerps to mouse (if not targetting)
angleLerpAm = 10;
attackDirection=45; //direction to next attack enemy from
naturalAngle = 45
attackFloatDist=16;
maxTargetRange = 32;
canAttack=false;
attackDl=0;
attackDlMax=20;
attacking=false;
attackTime=0
attackTimeMax=5
attackSpinSpeed=0;
xTo=x;
yTo=y;
hsp=0;
vsp=0;
targX=0;
targY=0;
bloodCount=10;
freeRoam=true;
spin=false
spinStart=0
image_speed=0