hsp=0;
vsp=0;
walkSpd = 0.25;
jumpPower = 3
grv = 0.2
jumpBuffer = 0
sprite_index=mageIdleLower_s
frictGround = 1.15
frictAir = 1.1
drawAng=0
spriteUpper=mageIdleLower_s
imageUpper=0
lastIndex=0
upperImageSpeed=0
attacking=0
goalDistance=96
goalBuffer=16
target=noone
edgeAvoidDist=12
attackDl=0
attackDlMax = 150
viewMaxRange = 200
knifeThrown=false
hitTime=0
hpMax=hp