hsp=0;
vsp=0;
walkSpd = 0.25;
jumpPower = 3
grv = 0.2
jumpBuffer = 0
sprite_index=archerIdleLower_s
frictGround = 1.15
frictAir = 1.1
drawAng=0
spriteUpper=archerIdleLower_s
imageUpper=0
lastIndex=0
upperImageSpeed=0
attacking=0
goalDistance=64
goalBuffer=16
target=noone
edgeAvoidDist=12