scabbard = instance_create_layer(x,y,"scabbard",scabbard_o);
//sword = instance_create_layer(x,y,"sword",sword_o);
//sword.hero=self;
sword = noone
scabbard.hero=self;
scabbard.image_speed=0;
hsp=0;
vsp=0;
playerControl = true;
walkSpd = 0.35;
jumpPower = 4
grv = 0.2
jumpBuffer = 0
sprite_index=heroIdleLower_s
frictGround = 1.15
frictAir = 1.1
drawAng=0
flipping = false
flipAllowed=false
flipped=false
drawing=0
spriteUpper=heroIdleLower_s
imageUpper=0
lastIndex=0
upperImageSpeed=0
oldTimeSpeed=1
hitTime=0
distanceCovered=0
footstepDistance=32
vspMax=10
hp=3
honour=20
honourInit=honour
honourWarned=false
hpLast=hp